# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TAMMAssessment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TAMMAssessment
pod 'RealmSwift'

  target 'TAMMAssessmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TAMMAssessmentUITests' do
    # Pods for testing
  end

end
